### ISSUE TITLE
README.md edit

### ISSUE THREAD

**Issue by Quantme** [shayanderson/xap#1]
In the section **Insert** into the `replace` command example:
`$affected_rows = xap('users:replace', ['id' => 5 'fullname' => 'Name Here',
    'is_active' => 1, 'created' => ['NOW()']]);`

should be:

`$affected_rows = xap('users:replace', ['id' => 5, 'fullname' => 'Name Here',
    'is_active' => 1, 'created' => ['NOW()']]);`

**Comment by shayanderson** [comment]
Thanks for the fix
